//  Dane postaci

const cArt = {
    Arlan: {
        path: 'CharacterArt/Arlan.webp',
        name: 'Arlan',
        element: 'Lighting',
        element_icon:'Element/Element_Lighting64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Arlan_Splash_Art.webp",
        basic_attack_name:'Lightning Rush',
        basic_attack_ani:'Skills/Character_Arlan_Ultimate.webp',
        basic_attack_desc:'Deals Lightning DMG equal to 50% of Arlan\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Shackle Breaker',
        skill_ani:'Skills/Character_Arlan_Ultimate.webp',
        skill_desc:'Consumes Arlan\'s HP equal to 15% of his Max HP to deal Lightning DMG equal to 160% of Arlan\'s ATK to a single enemy. This Skill cannot be used if Arlan\'s HP is too low.',
        skill_icon:"Path/Path_The_Abundance64.webp",
        ulti_name:'Frenzied Punishment',
        ulti_ani:'Skills/Character_Arlan_Ultimate.webp',
        ulti_desc:'Deals Lightning DMG equal to 210% of Arlan\'s ATK to a single enemy and Lightning DMG equal to 90% of Arlan\'s ATK to any adjacent enemies.',
        ulti_icon:"",
        talent_name:'Pain and Anger',
        talent_desc:'Increases Arlan\'s DMG for every percent of HP below his Max HP, up to a max of 40% more DMG.',
        talent_icon:"",
        technique_name:'Swift Harvest',
        technique_desc:'Immediately attacks the enemy. After entering battle, deals Lightning DMG equal to 80% of Arlan\'s ATK to all enemies.',
        technique_icon:"Path/Path_The_Abundance64.webp",
        eidelon_1_name:"To the Bitter End",
        eidelon_1_desc:"Arlan's Skill can be used so long as his current HP percentage is above or equal to 5%. If his current HP is less than 15%, using his Skill will reduce his HP to 1.",
        eidelon_1_icon:"",
        eidelon_2_name:"Breaking Free",
        eidelon_2_desc:"Skill DMG increases by 10%. When using Skill, dispels a debuff inflicted on Arlan.",
        eidelon_2_icon:"",
        eidelon_3_name:"Power Through",
        eidelon_3_desc:"Skill Lv. +2, up to a maximuum of Lv. 15. Basic ATK Lv. +1, up to a maximuum of Lv. 10.",
        eidelon_3_icon:"",
        eidelon_4_name:"Turn the Tables",
        eidelon_4_desc:"When struck by a killing blow, instead of becoming incapacitated, Arlan immediately restores his HP to 25% of his Max HP.This effect can only trigger 1 time per battle.",
        eidelon_4_icon:"",
        eidelon_5_name:"Hammer and Tongs",
        eidelon_5_desc:"Ultimate Lv. +2, up to a maximuum of Lv. 15. Talent Lv. +2, up to a maximuum of Lv. 15.",
        eidelon_5_icon:"",
        eidelon_6_name:"Self-Sacrifice",
        eidelon_6_desc:"When Arlan's HP is lower than 50% of his Max HP, increase his Ultimate's DMG by 20% and the DMG multiplier on adjacent targets increases to that of the target enemy.",
        eidelon_6_icon:""
    },
    Asta: {
        path: 'CharacterArt/Asta.webp',
        name: 'Asta',
        element: 'Fire',
        element_icon:'Element/Element_Fire64.webp',
        aion: 'Harmony',
        aion_icon:'Path/Path_The_Harmony64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Asta_Splash_Art.webp",
        basic_attack_name:'Spectrum Beam',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Fire DMG equal to 50/100/110% of Asta\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Meteor Storm',
        skill_ani:'',
        skill_desc:'Deals Fire DMG equal to 25/50/55% of Asta\'s ATK to a single enemy with 4 more bombardments. Each bombardment deals Fire DMG equal to 25/50/55% of Asta\'s ATK to a random enemy.',
        skill_icon:"Path/Path_The_Abundance64.webp",
        ulti_name:'Astral Blessing',
        ulti_ani:'Skills/Character_Asta_Ultimate.webp',
        ulti_desc:'Increases SPD of all allies by 36/45/50 for 2 turn(s).',
        ulti_icon:"",
        talent_name:'Astrometry',
        talent_desc:'Gains a Charging stack for every different enemy hit by Asta plus an additional stack if the enemy hit has Fire Weakness. For every Charging stack Asta has, all allies\' ATK increases by 5/10/11%, up to 5 time(s). Starting from her second turn, Asta\'s Charging stack count is reduced by 3 at the beginning of every turn.',
        talent_icon:"",
        technique_name:'Miracle Flash',
        technique_desc:'Immediately attacks the enemy. After entering battle, deals Fire DMG equal to 50% of Asta\'s ATK to all enemies.',
        technique_icon:"Path/Path_The_Abundance64.webp",
    },
    Bailu: {
        path: 'CharacterArt/Bailu.webp',
        name: 'Bailu',
        element: 'Lighting',
        element_icon:'Element/Element_Lighting64.webp',
        aion: 'Abundance',
        aion_icon:'Path/Path_The_Abundance64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Bailu_Splash_Art.webp",
        basic_attack_name:'Diagnostic Kick',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Lightning DMG equal to 50/100/110% of Bailu\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Singing Among Clouds',
        skill_ani:'',
        skill_desc:'Heals a single ally for 8/16/18% of Bailu\'s Max HP plus 64/128/138. Bailu then heals a single ally 2 more time(s). After each healing, the Outgoing Healing for the next healing is reduced by 15%.',
        skill_icon:"",
        ulti_name:'Leap of a Marsh Drakon',
        ulti_ani:'',
        ulti_desc:'Heals all allies for 10/18/20% of Bailu\'s Max HP plus 72/144/155. For allies that are not already "Invigorated", Bailu "Invigorates" them. For those who are already "Invigorated," Bailu makes their "Invigoration" last 1 more turn. "Invigoration" can last for 2 turn(s). This effect cannot stack.',
        ulti_icon:"",
        talent_name:'Gourdful of Elixir',
        talent_desc:'When an Invigorated ally is hit, heals the ally for 5/10/11% of Bailu\'s Max HP plus 50/100/108. This effect can trigger for up to 2 time(s). When an ally is knocked down, Bailu immediately heals them for 22/30/31% of Bailu\'s Max HP plus 180/240/249. This effect can only be triggered 1 time per battle.',
        talent_icon:"",
        technique_name:'Saunter in the Rain',
        technique_desc:'After using Bailu\'s Technique, at the start of the next battle, all allies are Invigorated for 1 turn(s).',
        technique_icon:"",
    },
    Blade: {
        path: 'CharacterArt/Blade.webp',
        name: 'Blade',
        element: 'Lighting',
        element_icon:'Element/Element_Lighting64.webp',
        aion: 'Abundance',
        aion_icon:'Path/Path_The_Abundance64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Bailu_Splash_Art.webp",
        basic_attack_name:'Diagnostic Kick',
        basic_attack_ani:'',
        basic_attack_desc:'Deals <span class="Lighting">Lightning DMG</span> equal to 50/100/110% of Bailu\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Singing Among Clouds',
        skill_ani:'',
        skill_desc:'Heals a single ally for 8/16/18% of Bailu\'s Max HP plus 64/128/138. Bailu then heals a single ally 2 more time(s). After each healing, the Outgoing Healing for the next healing is reduced by 15%.',
        skill_icon:"",
        ulti_name:'Leap of a Marsh Drakon',
        ulti_ani:'',
        ulti_desc:'Heals all allies for 10/18/20% of Bailu\'s Max HP plus 72/144/155. For allies that are not already "Invigorated", Bailu "Invigorates" them. For those who are already "Invigorated," Bailu makes their "Invigoration" last 1 more turn. "Invigoration" can last for 2 turn(s). This effect cannot stack.',
        ulti_icon:"",
        talent_name:'Gourdful of Elixir',
        talent_desc:'When an Invigorated ally is hit, heals the ally for 5/10/11% of Bailu\'s Max HP plus 50/100/108. This effect can trigger for up to 2 time(s). When an ally is knocked down, Bailu immediately heals them for 22/30/31% of Bailu\'s Max HP plus 180/240/249. This effect can only be triggered 1 time per battle.',
        talent_icon:"",
        technique_name:'Saunter in the Rain',
        technique_desc:'After using Bailu\'s Technique, at the start of the next battle, all allies are Invigorated for 1 turn(s).',
        technique_icon:"",
    },
    Bronya: {
        path: 'CharacterArt/Bronya.webp',
        name: 'Bronya',
        element: 'Wind',
        element_icon:'Element/Element_Wind64.webp',
        aion: 'Harmony',
        aion_icon:'Path/Path_The_Harmony64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Bronya_Splash_Art.webp",
        basic_attack_name:'Windrider Bullet',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Wind DMG equal to 50/100/110% of Bronya\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Combat Redeployment',
        skill_ani:'',
        skill_desc:'Dispels a debuff from a single ally, Advances Forward their actions by 100%, and increases their DMG by 36/72/79% for 1 turn(s).',
        skill_icon:"",
        ulti_name:'The Belobog March',
        ulti_ani:'',
        ulti_desc:'Increases the ATK of all allies by 36/60/64%, and increase their CRIT DMG equal to 12/16/17% of Bronya\'s CRIT DMG plus 12/20/21% for 2 turn(s).',
        ulti_icon:"",
        talent_name:'Leading the Way',
        talent_desc:'After using her Basic ATK, Bronya\'s next action will be Advanced Forward by 15/30/33%.',
        talent_icon:"",
        technique_name:'Banner of Command',
        technique_desc:'After using Bronya\'s Technique, in the next battle, all allies\' ATK increases by 15% for 2 turn(s).',
        technique_icon:"",
    },
    Clara: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    DanHeng: {
        path: 'CharacterArt/DanHeng.webp',
        name: 'Dan Heng',
        element: 'Wind',
        element_icon:'Element/Element_Wind64.webp',
        aion: 'Hunt',
        aion_icon:'Path/Path_The_Hunt64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_DanHeng_Splash_Art.webp",
        basic_attack_name:'Knight Spear Technique: North Wind',
        basic_attack_ani:'',
        basic_attack_desc:'Deal Wind DMG equal to 50/100/110% of Dan Heng\'s ATK to a target enemy.',
        basic_attack_icon:"",
        skill_name:'Knight Spear Technique: Torrent',
        skill_ani:'',
        skill_desc:'Deals Wind DMG equal to 130/260/286% of Dan Heng\'s ATK to a single enemy. On a CRIT Hit, there is a 100% base chance to reduce the target\'s SPD by 15% for 2 turn(s).',
        skill_icon:"",
        ulti_name:'Ethereal Dream',
        ulti_ani:'',
        ulti_desc:'Deals Wind DMG equal to 240/400/432% of Dan Heng\'s ATK to a single enemy. If the enemy is Slowed, Dan Heng\'s Ultimate\'s DMG multiplier increases by 72/120/129%.',
        ulti_icon:"",
        talent_name:'Superiority of Reach',
        talent_desc:'When Dan Heng is the target of an ally\'s Ability, his next attack\'s Wind RES PEN increases by 18/36/39%. This effect can be triggered again after Dan Heng has taken action 1 time(s).',
        talent_icon:"",
        technique_name:'Splitting Spearhead',
        technique_desc:'After using a Technique, Dan Heng\'s ATK increases by 40% for 3 turn(s) in the next battle.',
        technique_icon:"",
    },
    FuXuan: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Gepard: {
        path: 'CharacterArt/Gepard.webp',
        name: 'Gepard',
        element: 'Ice',
        element_icon:'Element/Element_Ice64.webp',
        aion: 'Preservation',
        aion_icon:'Path/Path_The_Preservation64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Gepard_Splash_Art.webp",
        basic_attack_name:'Fist of Conviction',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Ice DMG equal to 50/100/110% of Gepard\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Intimidating Strike',
        skill_ani:'',
        skill_desc:'Deals Ice DMG equal to 100/200/220% of Gepard\'s ATK to a single enemy, with a 65% base chance to Freeze that enemy for 1 turn(s). While Frozen, the enemy cannot take action and will take Ice DoT equal to 25/50/55% of Gepard\'s ATK each turn.',
        skill_icon:"",
        ulti_name:'Enduring Bulwark',
        ulti_ani:'',
        ulti_desc:'Apply a Shield to all allies, absorbing DMG equal to 36/60/64% of Gepard\'s DEF plus 120/240/258 for 3 turn(s).',
        ulti_icon:"",
        talent_name:'Unyielding Will',
        talent_desc:'When struck with a killing blow, instead of becoming incapacitated, Gepard\'s HP immediately restores 25/50/55% of his Max HP. This effect can only trigger once per battle.',
        talent_icon:"",
        technique_name:'Comradery',
        technique_desc:'After using Gepard\'s Technique, when the next battle begins, applies a shield to all allies, absorbing DMG equal to 24% of Gepard\'s DEF plus 96 for 2 turn(s).',
        technique_icon:"",
    },
    Herta: {
        path: 'CharacterArt/Herta.webp',
        name: 'Herta',
        element: 'Ice',
        element_icon:'Element/Element_Ice64.webp',
        aion: 'Erudition',
        aion_icon:'Path/Path_The_Erudition64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Herta_Splash_Art.webp",
        basic_attack_name:'What Are You Looking At?',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Ice DMG equal to 50/100/110% of Herta\'s ATK to a single enemy. ',
        basic_attack_icon:"",
        skill_name:'One-Time Offer',
        skill_ani:'',
        skill_desc:'Deals Ice DMG equal to 50/100/110% of Herta\'s ATK to all enemies. If the enemy\'s HP is at 50% of their Max HP or higher, DMG dealt to this target increases by 20%.',
        skill_icon:"",
        ulti_name:'It\'s Magic, I Added Some Magic',
        ulti_ani:'',
        ulti_desc:'Deals Ice DMG equal to 120/200/216% of Herta\'s ATK to all enemies.',
        ulti_icon:"",
        talent_name:'I\'ll Take a Swing',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'It Can Still Be Optimized',
        technique_desc:'After using her Technique, Herta\'s ATK increases by 40% for 3 turn(s) in the next battle.',
        technique_icon:"",
    },
    Himeko: {
        path: 'CharacterArt/Himeko.webp',
        name: 'Himeko',
        element: 'Fire',
        element_icon:'Element/Element_Fire64.webp',
        aion: 'Erudition',
        aion_icon:'Path/Path_The_Erudition64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Himeko_Splash_Art.webp",
        basic_attack_name:'Sawblade Tuning',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Fire DMG equal to 50/100/110% of Himeko\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Molten Detonation',
        skill_ani:'',
        skill_desc:'Deals Fire DMG equal to 100/200/220% of Himeko\'s ATK to a single enemy and Fire DMG equal to 40/80/88% of Himeko\'s ATK to any adjacent enemies.',
        skill_icon:"",
        ulti_name:'Heavenly Flare',
        ulti_ani:'',
        ulti_desc:'Deals Fire DMG equal to 132/220/237% of Himeko\'s ATK to all enemies. Additionally, Himeko additionally regenerates 10 Energy for each enemy defeated.',
        ulti_icon:"",
        talent_name:'Victory Rush',
        talent_desc:'When an enemy\'s Weakness is Broken, Himeko gains a stack of Charge (max 3 stacks). If Himeko is fully Charged, deals Fire DMG equal to 68/136/149% of Himeko\'s ATK to all enemies after an ally performs an attack, and consumes all Charge stacks. Gains 1 stack of Charge at the beginning of the battle.',
        talent_icon:"",
        technique_name:'Incomplete Combustion',
        technique_desc:'After using Himeko\'s Technique, use a satellite beam to create a Burning Zone that lasts for 15 second(s). When entering battle in the Burning Zone, there is a 100% base chance to increase Fire DMG taken by enemies by 10% for 2 turn(s).',
        technique_icon:"",
    },
    Hook: {
        path: 'CharacterArt/Hook.webp',
        name: 'Hook',
        element: 'Fire',
        element_icon:'Element/Element_Fire64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Hook_Splash_Art.webp",
        basic_attack_name:'Hehe! Don\'t Get Burned!',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Fire DMG equal to 50/100/110% of Hook\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Hey! Remember Hook?',
        skill_ani:'',
        skill_desc:'Deals Fire DMG equal to 120/240/264% of Hook\'s ATK to a single enemy. In addition, there is a 100% base chance to inflict Burn for 2 turn(s). When afflicted with Burn, enemies will take Fire DoT equal to 25/50/55% of Hook\'s ATK at the beginning of each turn.',
        skill_icon:"",
        ulti_name:'Boom! Here Comes the Fire!',
        ulti_ani:'',
        ulti_desc:'Deals Fire DMG equal to 240/400/432% of Hook\'s ATK to a single enemy. After using her Ultimate, the next Skill to be used is Enhanced, which deals DMG to a target enemy and any adjacent enemies.',
        ulti_icon:"",
        talent_name:'Ha! Oil to the Flames!',
        talent_desc:'When Hook attacks a target inflicted with Burn, deals additional Fire DMG equal to 50/100/110% of Hook\'s ATK and additionally regenerates 5 Energy.',
        talent_icon:"",
        technique_name:'Ack! Look at This Mess!',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, Hook deals Fire DMG equal to 50% of her ATK to a random enemy. In addition, there is a 100% base chance to inflict Burn on all enemies for 3 turn(s). When afflicted with Burn, enemies will take Fire DoT equal to 50% of Hook\'s ATK at the beginning of each turn.',
        technique_icon:"",
    },
    JingYuan: {
        path: 'CharacterArt/JingYuan.webp',
        name: 'JingYuan',
        element: 'Lighting',
        element_icon:'Element/Element_Lighting64.webp',
        aion: 'Erudition',
        aion_icon:'Path/Path_The_Erudition64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_JingYuan_Splash_Art.webp",
        basic_attack_name:'Glistening Light',
        basic_attack_ani:'',
        basic_attack_desc:'Jing Yuan deals Lightning DMG equal to 50/100/110% of his ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Rifting Zenith',
        skill_ani:'',
        skill_desc:'Deals Lightning DMG equal to 50/100/110% of Jing Yuan\'s ATK to all enemies and increases Lightning-Lord\'s attack count by 2 for the next turn.',
        skill_icon:"",
        ulti_name:'Lightbringer',
        ulti_ani:'',
        ulti_desc:'Deals Lightning DMG equal to 120/200/216% of Jing Yuan\'s ATK to all enemies and increases Lightning-Lord\'s attack count by 3 for the next turn.',
        ulti_icon:"",
        talent_name:'Prana Extirpated',
        talent_desc:'Summons Lightning-Lord at the start of the battle. Lightning-Lord has 60 base SPD and 3 base attack count, and its attacks are considered follow-up attacks. Each count of Lightning-Lord\'s attack deals Lightning DMG equal to 33/66/72% of Jing Yuan\'s ATK to a single enemy, whose adjacent targets also receive Lightning DMG equal to 25% of the DMG dealt to the main target. The Lightning-Lord\'s attack count can reach a max of 10. Every time Lightning-Lord\'s attack count increases by 1, its SPD increases by 10. After the action ends, SPD and attack count return to their base values. When Jing Yuan is knocked down, the Lightning-Lord will disappear. When Jing Yuan is affected by Crowd Control debuff, the Lightning-Lord is unable to take action.',
        talent_icon:"",
        technique_name:'Command Talisman',
        technique_desc:'After using Jing Yuan\'s Technique, Lightning-Lord\'s attack count in the first turn increases by 2 at the start of the next battle.',
        technique_icon:"",
    },
    Kafka: {
        path: 'CharacterArt/Kafka.webp',
        name: 'Kafka',
        element: 'Lighting',
        element_icon:'Element/Element_Lighting64.webp',
        aion: 'Nihility',
        aion_icon:'Path/Path_The_Nihility64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Kafka_Splash_Art.webp",
        basic_attack_name:'Midnight Tumult',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Lightning DMG equal to 50/100/110% of Kafka\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Caressing Moonlight',
        skill_ani:'',
        skill_desc:'Deals Lightning DMG equal to 70/140/154% of Kafka\'s ATK to a single enemy and Lightning DMG equal to 25/50/55% of Kafka\'s ATK to any adjacent enemies. If the main target enemy is currently receiving DoT, all DoTs currently on that enemy will immediately apply DMG equal to 100/125/130% of their DoT DMG Multiplier.',
        skill_icon:"",
        ulti_name:'Twilight Trill',
        ulti_ani:'',
        ulti_desc:'Deals Lightning DMG equal to 36/60/64% of Kafka\'s ATK to all enemies, with a 100% base chance for enemies hit to become Shocked and immediately take DMG equal to 80/100/104% of the original DMG received. Shock lasts for 3 turn(s). When Shocked, enemies receive Lightning DoT equal to 60/100/108% of Kafka\'s ATK at the beginning of each turn.',
        ulti_icon:"",
        talent_name:'Gentle but Cruel',
        talent_desc:'After an ally uses Basic ATK on a Shocked enemy, Kafka immediately deals Lightning DMG equal to 75/150/165% of her ATK to that enemy. This effect can only be triggered once per turn.',
        talent_icon:"",
        technique_name:'Mercy Is Not Forgiveness',
        technique_desc:'When using a Technique to enter battle, deals 50% of Kafka\'s ATK as Lightning DMG to a random enemy. At the same time, all enemies have a 100% base chance to be Shocked for 3 turn(s). While Shocked, enemies will take 50% of Kafka\'s ATK as Lightning DoT at the start of each turn.',
        technique_icon:"",
    },
    Luocha: {
        path: 'CharacterArt/Luocha.webp',
        name: 'Luocha',
        element: 'Imaginary',
        element_icon:'Element/Element_Imaginary64.webp',
        aion: 'Abundance',
        aion_icon:'Path/Path_The_Abundance64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Luocha_Splash_Art.webp",
        basic_attack_name:'Thorns of the Abyss',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Imaginary DMG equal to 50/100/110% of Luocha\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Prayer of Abyss Flower',
        skill_ani:'',
        skill_desc:'After using his Skill, immediately restore a single ally\'s HP equal to 48/80/86% of Luocha\'s ATK plus 160/320/344. Meanwhile, Luocha gains 1 stack of Abyss Flower. When an ally\'s HP drops below 50%, Luocha will immediately use his Skill 1 time on this ally (without consuming Skill Points). This effect can be triggered again when the conditions are met after Luocha takes action 2 more time(s).',
        skill_icon:"",
        ulti_name:'Death Wish',
        ulti_ani:'',
        ulti_desc:'Dispels 1 enemy buff(s) and deals Imaginary DMG equal to 80/160/176% of Luocha\'s ATK to all enemies. For every enemy buff dispelled, Luocha gains 1 stack of Abyss Flower.',
        ulti_icon:"",
        talent_name:'Cycle of Life',
        talent_desc:'When Abyss Flower is stacked 3 time(s), Luocha consumes all stacks to deploy a Field against the enemy. When any enemy in the Field is attacked by an ally, the ally immediately restores HP equal to 15/25/27% of Luocha\'s ATK plus 50/100/108. The Field effect lasts 2 turn(s). ',
        talent_icon:"",
        technique_name:'Mercy of a Fool',
        technique_desc:'After using his Technique, Luocha immediately heals an ally with the lowest current HP percentage equal to 50% of Luocha\'s Max HP.',
        technique_icon:"",
    },
    March7th: {
        path: 'CharacterArt/March7th.webp',
        name: 'March7th',
        element: 'Ice',
        element_icon:'Element/Element_Ice64.webp',
        aion: 'Preservation',
        aion_icon:'Path/Path_The_Preservation64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_March_7th_Splash_Art.webp",
        basic_attack_name:'Frigid Cold Arrow',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Ice DMG equal to 50/100/110% of March 7th\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'The Power of Cuteness',
        skill_ani:'',
        skill_desc:'Provides a single ally with a Shield that can absorb DMG equal to 48/80/86% of March 7th\'s DEF plus 160/320/344 for 3 turn(s). If the ally\'s HP is 30% of their Max HP or higher, greatly increases the chance of enemies attacking that ally.',
        skill_icon:"",
        ulti_name:'Glacial Cascade',
        ulti_ani:'',
        ulti_desc:'Deals Ice DMG equal to 90/150/162% of March 7th\'s ATK to all enemies. On a hit, the enemy has a 50% base chance to be Frozen for 1 turn(s). While Frozen, the enemy cannot act and will take Ice DoT equal to 30/50/54% of March 7th\'s ATK at the beginning of each turn. ',
        ulti_icon:"",
        talent_name:'Girl Power',
        talent_desc:'After a shielded ally is attacked by an enemy, March 7th immediately Counters, dealing Ice DMG equal to 50/100/110% of her ATK. This effect can be triggered 2 time(s) each turn.',
        talent_icon:"",
        technique_name:'Freezing Beauty',
        technique_desc:'Immediately attacks the enemy. After entering battle, there is a 100% base chance to Freeze a random enemy for 1 turn(s). While Frozen, the enemy cannot move and will take Ice DMG equal to 50% of March 7th\'s ATK at the beginning of each turn.',
        technique_icon:"",
    },
    Natasha: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Pela: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Qingque: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Sampo: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Seele: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    SilverWolf: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Serval: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Sushang: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Tingyun: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Welt: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    },
    Yanqing: {
        path: 'CharacterArt/Clara.webp',
        name: 'Clara',
        element: 'Physical',
        element_icon:'Element/Element_Physical64.webp',
        aion: 'Destruction',
        aion_icon:'Path/Path_The_Destruction64.webp',
        lore:"LOREM IPSUM",
        quote:"The BEST",
        splash_art:"SplashArt/Character_Clara_Splash_Art.webp",
        basic_attack_name:'I Want to Help',
        basic_attack_ani:'',
        basic_attack_desc:'Deals Physical DMG equal to 50/100/110% of Clara\'s ATK to a single enemy.',
        basic_attack_icon:"",
        skill_name:'Svarog Watches Over You',
        skill_ani:'',
        skill_desc:'Deals Physical DMG equal to <b>60/120/132%</b> of Clara\'s ATK to all enemies; deals additional Physical DMG equal to 60/120/132% of Clara\'s ATK to enemies marked by Svarog with a Mark of Counter. All Marks of Counter will be removed after Skill is used.',
        skill_icon:"",
        ulti_name:'Promise, Not Command',
        ulti_ani:'',
        ulti_desc:'After using her Ultimate, DMG dealt to Clara is reduced by an additional 15/25/27%, and Clara has a greatly increased chance of being attacked by enemies for 2 turn(s). In addition, Svarog\'s Counter is enhanced. When an ally is attacked, Svarog is guaranteed to launch Counters, with its Counter DMG multiplier on the enemy increases by 96/160/172%. Adjacent enemies take 50% of the DMG dealt to the target enemy. Enhanced Counter can take effect 2 time(s).',
        ulti_icon:"",
        talent_name:'Because We\'re Family',
        talent_desc:'Under the protection of Svarog, Clara\'s DMG taken is reduced by 15%. Svarog will mark enemies who attack Clara with Mark of Counter and retaliate with a Counter, dealing Physical DMG equal to 80/160/176% of Clara\'s ATK.',
        talent_icon:"",
        technique_name:'Small Price For Victory',
        technique_desc:'Immediately attacks the enemy. Upon entering battle, the chance Clara will be attacked by enemies increases for 2 turn(s).',
        technique_icon:"",
    }
};

/* Wyświetlanie portretów postaci w oparciu o ich nazwe ID na stronie index.html*/

$(document).ready(function(){
    $(".tag").each(function(){
        var id = $(this).attr("id");
        if (id in cArt) {
            $(this).css({
                "content": "url('" + cArt[id].path + "')",
                "name": cArt[id].name
            });
        }
    });
});



/* Zmiana danych w oknie informacji o postaci.

$(document).ready(function() {
    $(".tag").click(function() {
      const id = $(this).attr("id");
      const character = cArt[id];
      const name = character.name;
      const element = character.element;
      const aion = character.aion;
      $('#name-container').text(name);
      $('#element-container').text(element);
      $('#path-container').text(aion);
    });
  });

*/

